spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wt3db
    password: 4021
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true